# TNS for MARS 7i-93
DbUrl-93=jdbc\:oracle\:thin\:@192.168.169.55\:1600\:IND56

# TNS for MARS 7i-83
DbUrl-83=jdbc\:oracle\:thin\:@192.168.169.55\:1600\:IND61

# TNS for MARS 9-165 [Automation database is same for 165 and 168 URLs]
DbUrl-165=jdbc\:oracle\:thin\:@192.168.169.138\:1721\:IND206
DbUrl-168=jdbc\:oracle\:thin\:@192.168.169.55\:1600\:IND60
DbUrl-163=jdbc\:oracle\:thin\:@192.168.169.101\:1741\:IND108
DbUrl-172=jdbc\:oracle\:thin\:@192.168.169.138\:1721\:IND301

# Credentials for database 
DbUrl=jdbc\:oracle\:thin\:@192.168.169.138\:1721\:IND206
DbUser=AMARS
DbPassword=AMARS


# Test Execution Tracking Parameters [Mars9-165, Mars9-168, Mars7i-93, Mars7i-83]
TestExecutionOn=
Release=
Category=
LapTime=120000
ServerUrl=
